# Copyright Luc Yriarte <luc.yriarte@thingagora.org> 2018 
# License: Apache-2.0

Organizations:
  - &ThingagoraBC0Orderer
      Name: ThingagoraBC0Orderer
      ID: ThingagoraBC0OrdererMSP
      MSPDir: crypto-config/ordererOrganizations/or-bc0.thingagora.org/msp
      Policies: &BlockchainCoopDefaults
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"
        BlockValidation:
          Type: ImplicitMeta
          Rule: "ANY Writers"
  - &ThingagoraBC0Peer
      Name: ThingagoraBC0Peer
      ID: ThingagoraBC0PeerMSP
      MSPDir: crypto-config/peerOrganizations/pr-bc0.thingagora.org/msp
      Policies: *BlockchainCoopDefaults
      AnchorPeers:
        - Host: peer0.pr-bc0.thingagora.org
          Port: 7151
  - &OpenflowBC0Peer
      Name: OpenflowBC0Peer
      ID: OpenflowBC0PeerMSP
      MSPDir: crypto-config/peerOrganizations/pr-bc0.openflow.legal/msp
      Policies: *BlockchainCoopDefaults
      AnchorPeers:
        - Host: peer0.pr-bc0.openflow.legal
          Port: 7151

Capabilities:
    Channel: &ChannelCapabilities
        V1_3: true

    Orderer: &OrdererCapabilities
        V1_1: true

    Application: &ApplicationCapabilities
        V1_3: true
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    ACLs: &ACLsDefault
        lscc/ChaincodeExists: /Channel/Application/Readers
        lscc/GetDeploymentSpec: /Channel/Application/Readers
        lscc/GetChaincodeData: /Channel/Application/Readers
        lscc/GetInstantiatedChaincodes: /Channel/Application/Readers
        qscc/GetChainInfo: /Channel/Application/Readers
        qscc/GetBlockByNumber: /Channel/Application/Readers
        qscc/GetBlockByHash: /Channel/Application/Readers
        qscc/GetTransactionByID: /Channel/Application/Readers
        qscc/GetBlockByTxID: /Channel/Application/Readers
        cscc/GetConfigBlock: /Channel/Application/Readers
        cscc/GetConfigTree: /Channel/Application/Readers
        cscc/SimulateConfigTreeUpdate: /Channel/Application/Readers
        peer/Propose: /Channel/Application/Writers
        peer/ChaincodeToChaincode: /Channel/Application/Readers
        event/Block: /Channel/Application/Readers
        event/FilteredBlock: /Channel/Application/Readers

    Organizations:

    Policies: &ApplicationDefaultPolicies
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
      - orderer0.or-bc0.thingagora.org:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    MaxChannels: 0
    Organizations:
    Policies: *BlockchainCoopDefaults

Channel: &ChannelDefaults
    Policies:
        <<: *ApplicationDefaultPolicies
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    ThingagoraBC0OrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *ThingagoraBC0Orderer
        Consortiums:
            BlockchainCoopBC0Consortium:
                Organizations:
                    - <<: *ThingagoraBC0Peer
                      Policies:
                          <<: *ApplicationDefaultPolicies
                    - <<: *OpenflowBC0Peer
                      Policies:
                          <<: *ApplicationDefaultPolicies

    BlockchainCoopBC0PeerChannels:
        <<: *ChannelDefaults
        Consortium: BlockchainCoopBC0Consortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
               - <<: *ThingagoraBC0Peer
                 Policies:
                     <<: *ApplicationDefaultPolicies
               - <<: *OpenflowBC0Peer
                 Policies:
                     <<: *ApplicationDefaultPolicies
