# Copyright Luc Yriarte <luc.yriarte@thingagora.org> 2018 
# License: Apache-2.0

Organizations:
  - &ThingagoraBC0Orderer
      Name: ThingagoraBC0Orderer
      ID: ThingagoraBC0OrdererMSP
      MSPDir: crypto-config/ordererOrganizations/or-bc0.thingagora.org/msp
      Policies: &BlockchainDefaults
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"
        BlockValidation:
          Type: ImplicitMeta
          Rule: "ANY Writers"
  - &ThingagoraBC0Peer
      Name: ThingagoraBC0Peer
      ID: ThingagoraBC0PeerMSP
      MSPDir: crypto-config/peerOrganizations/pr-bc0.thingagora.org/msp
      Policies: *BlockchainDefaults
      AnchorPeers:
        - Host: peer0.pr-bc0.thingagora.org
          Port: 7151

Application: &ApplicationDefaults
    Organizations:
    Policies: *BlockchainDefaults

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
      - orderer0.or-bc0.thingagora.org:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    MaxChannels: 0
    Organizations:
    Policies: *BlockchainDefaults

Profiles:
    BC0OrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *ThingagoraBC0Orderer
        Consortiums:
            BC0Consortium:
                Organizations:
                    - *ThingagoraBC0Peer

    BC0PeerChannels:
        Consortium: BC0Consortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *ThingagoraBC0Peer
