# Copyright Luc Yriarte <luc.yriarte@thingagora.org> 2018 
# License: Apache-2.0

version: '2'

networks:
  homenet:

services:
  ca.mauguio.yriarte.org:
    container_name: ca
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/ca/ca.mauguio.yriarte.org-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/ca/${ca__CA_KEYFILE}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/tlsca/tlsca.mauguio.yriarte.org-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/tlsca/${ca__TLS_KEYFILE}
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b ${ca__ADMIN}:${ca__PASSWD} -d'
    volumes:
      - ./crypto-config/peerOrganizations/mauguio.yriarte.org/ca/:/etc/hyperledger/ca/
      - ./crypto-config/peerOrganizations/mauguio.yriarte.org/tlsca/:/etc/hyperledger/tlsca/
    networks:
      - homenet

  orderer.yriarte.org:
    container_name: orderer
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/config/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=YriarteOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/:/etc/hyperledger/config
        - ./crypto-config/ordererOrganizations/yriarte.org/orderers/orderer.yriarte.org/msp/:/etc/hyperledger/msp
        - ./crypto-config/ordererOrganizations/yriarte.org/orderers/orderer.yriarte.org/tls/:/etc/hyperledger/tls
    networks:
      - homenet

  teleron.mauguio.yriarte.org:
    container_name: teleron
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_homenet
      - CORE_PEER_ID=teleron.mauguio.yriarte.org
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=YriarteMauguioMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/
      - CORE_PEER_ADDRESS=teleron.mauguio.yriarte.org:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-teleron.mauguio.yriarte.org:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=${telerondb__USERNAME}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=${telerondb__PASSWORD}
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/mauguio.yriarte.org/peers/teleron.mauguio.yriarte.org/msp:/etc/hyperledger/msp/
        - ./crypto-config/peerOrganizations/mauguio.yriarte.org/peers/teleron.mauguio.yriarte.org/tls:/etc/hyperledger/tls/
    depends_on:
      - couchdb-teleron.mauguio.yriarte.org
    networks:
      - homenet

  couchdb-teleron.mauguio.yriarte.org:
    container_name: couchdb-teleron
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=${telerondb__USERNAME}
      - COUCHDB_PASSWORD=${telerondb__PASSWORD}
    ports:
      - 5984:5984
    networks:
      - homenet

  cli-teleron.mauguio.yriarte.org:
    container_name: cli-teleron
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_PEER_ID=cli-teleron.mauguio.yriarte.org
      - CORE_PEER_ADDRESS=teleron.mauguio.yriarte.org:7051
      - CORE_PEER_LOCALMSPID=YriarteMauguioMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/admin/msp/
      - CORE_CHAINCODE_KEEPALIVE=10
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/admin/tls/client.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/admin/tls/client.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/admin/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/blockchain-coop/
        - ./crypto-config/peerOrganizations/mauguio.yriarte.org/users/Admin@mauguio.yriarte.org/:/etc/hyperledger/admin/
        - ./crypto-config/ordererOrganizations/yriarte.org/tlsca/:/etc/hyperledger/orderer/
        - ./config/:/etc/hyperledger/config/
    networks:
        - homenet

