# Copyright Luc Yriarte <luc.yriarte@thingagora.org> 2019
# License: Apache-2.0

Organizations:
  - &ChainOpsBC1Orderer
      Name: ChainOpsBC1Orderer
      ID: ChainOpsBC1OrdererMSP
      MSPDir: crypto-config/ordererOrganizations/or-bc1.chain-ops.net/msp
  - &ChainOpsBC1Peer
      Name: ChainOpsBC1Peer
      ID: ChainOpsBC1PeerMSP
      MSPDir: crypto-config/peerOrganizations/pr-bc1.chain-ops.net/msp
      AnchorPeers:
        - Host: peer0.pr-bc1.chain-ops.net
          Port: 7051
  - &CivisBlockchainBC1Peer
      Name: CivisBlockchainBC1Peer
      ID: CivisBlockchainBC1PeerMSP
      MSPDir: crypto-config/peerOrganizations/pr-bc1.civis-blockchain.org/msp
      AnchorPeers:
        - Host: peer0.pr-bc1.civis-blockchain.org
          Port: 7051
  - &ThingagoraBC1Peer
      Name: ThingagoraBC1Peer
      ID: ThingagoraBC1PeerMSP
      MSPDir: crypto-config/peerOrganizations/pr-bc1.thingagora.org/msp
      AnchorPeers:
        - Host: peer0.pr-bc1.thingagora.org
          Port: 7051

Capabilities:
    Channel: &ChannelCapabilities
        V1_3: true

    Orderer: &OrdererCapabilities
        V1_1: true

    Application: &ApplicationCapabilities
        V1_3: true
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    ACLs: &ACLsDefault
        lscc/ChaincodeExists: /Channel/Application/Readers
        lscc/GetDeploymentSpec: /Channel/Application/Readers
        lscc/GetChaincodeData: /Channel/Application/Readers
        lscc/GetInstantiatedChaincodes: /Channel/Application/Readers
        qscc/GetChainInfo: /Channel/Application/Readers
        qscc/GetBlockByNumber: /Channel/Application/Readers
        qscc/GetBlockByHash: /Channel/Application/Readers
        qscc/GetTransactionByID: /Channel/Application/Readers
        qscc/GetBlockByTxID: /Channel/Application/Readers
        cscc/GetConfigBlock: /Channel/Application/Readers
        cscc/GetConfigTree: /Channel/Application/Readers
        cscc/SimulateConfigTreeUpdate: /Channel/Application/Readers
        peer/Propose: /Channel/Application/Writers
        peer/ChaincodeToChaincode: /Channel/Application/Readers
        event/Block: /Channel/Application/Readers
        event/FilteredBlock: /Channel/Application/Readers

    Organizations:

    Policies: &ApplicationDefaultPolicies
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
      - orderer0.or-bc1.chain-ops.net:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 10 MB
        PreferredMaxBytes: 512 KB
    MaxChannels: 0
    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

    Capabilities:
        <<: *OrdererCapabilities

Channel: &ChannelDefaults
    Policies:
        <<: *ApplicationDefaultPolicies
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    ChainOpsBC1OrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - <<: *ChainOpsBC1Orderer
                  Policies:
                      <<: *ApplicationDefaultPolicies
        Consortiums:
            BlockchainCoopBC1Consortium:
                Organizations:
                    - <<: *ChainOpsBC1Peer
                      Policies:
                          <<: *ApplicationDefaultPolicies
                    - <<: *CivisBlockchainBC1Peer
                      Policies:
                          <<: *ApplicationDefaultPolicies
                    - <<: *ThingagoraBC1Peer
                      Policies:
                          <<: *ApplicationDefaultPolicies

    BlockchainCoopBC1PeerChannels:
        <<: *ChannelDefaults
        Consortium: BlockchainCoopBC1Consortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - <<: *ChainOpsBC1Peer
                  Policies:
                      <<: *ApplicationDefaultPolicies
                - <<: *CivisBlockchainBC1Peer
                  Policies:
                      <<: *ApplicationDefaultPolicies
                - <<: *ThingagoraBC1Peer
                  Policies:
                      <<: *ApplicationDefaultPolicies

